# version: "3"
services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mysql
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8
    
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=hafta
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
      - 33060

  backend:
    build:
      context: backend
    
    secrets:
      - db-password
    
    networks:
      - backnet
     
    depends_on:
      db:
        condition: service_healthy

  frontend: 
    build:
      context: front
    ports:
      - 8000:8000
    networks:
      - frontnet

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet:
  