# version: "3"
services:
  backend:
    build: backend
    restart: always
    # secrets:
    #   - db_password
    environment:
      MYSQL_HOST: db
    networks:
      # - vue-python
      - python-mysql
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: hafta
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    # secrets:
    #   - db_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - python-mysql

volumes:
  db-data: {}

# secrets:
#   db_password:
#     file: db/password.txt

networks:
  python-mysql:
    {}
    # driver: bridge
