services:
  db:
    image: mysql

    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
      
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=hafta
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
      - 33060

  backend:
    build:
      context: backend
    ports:
      - 8000:8000
    
    networks:
      - backnet
      - frontnet
     
    depends_on:
      db:
        condition: service_healthy

  frontend: 
    build:
      context: front
    ports: 
      - 80:80
    
    depends_on:
      - backend
    networks:
      - frontnet
      
volumes:
  db-data:

networks:
  backnet:
  frontnet:
  